sudo: required

services: docker

env:
  global:
    - TARGET="GHCR"

  matrix:
    - VERSION=15.0
    - VERSION=16.0
    - VERSION=14.0
    - VERSION=14.0-bullseye
    - VERSION=13.0
    - VERSION=12.0
    - VERSION=11.0
#    - VERSION=10.0
#    - VERSION=9.0
#    - VERSION=8.0
#    - VERSION=7.0

script:
  - make VERSION=$VERSION build
  - make VERSION=$VERSION test

# Need docker-ce 20 instead of docker-ce 18 for building Odoo 15 on debian:bullseye
# https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
before_install:
  - if [ "$VERSION" = "15.0" OR "$VERSION" = "16.0" ] ; then curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - ; fi
  - if [ "$VERSION" = "15.0" OR "$VERSION" = "16.0" ] ; then sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" ; fi
  - if [ "$VERSION" = "15.0" OR "$VERSION" = "16.0" ] ; then sudo apt-get update ; fi
  - if [ "$VERSION" = "15.0" OR "$VERSION" = "16.0" ] ; then sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce ; fi
  - docker --version

after_success:
  - travis/publish.sh
