sudo: required

services: docker

env:
  matrix:
    - VERSION=13.0
    - VERSION=12.0
    - VERSION=11.0
    - VERSION=10.0
    - VERSION=9.0
    - VERSION=8.0
    - VERSION=7.0

script:
  - make VERSION=$VERSION build
  - make VERSION=$VERSION test

after_success:
  - travis/publish.sh
